
services:
  - type: web
    name: sofascore-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_sofascore.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
